# Site settings
title: 'Misguided Ramblings' # Your Title
tagline: 'The word vomit of an intrepid young web developer' # A brief tagline for your site
sidebar_image: /images/cover.jpg
#url: "http://arxene.github.io/misguidedramblings"
url: "localhost:4000"
baseurl: "/misguidedramblings"
github_username: arxene

# Build settings
markdown: kramdown
highlighter: pygments

# Global settings
timezone: America/Chicago