# Site settings
title: Misguided Ramblings
email: ray.mcmahan1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Ray McMahan to keep track of learning progress and everyday musings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arxene.github.io/misguidedramblings" # the base hostname & protocol for your site
github_username: arxene

# Build settings
markdown: kramdown

# Global settings
timezone: America/Chicago